import { Metadata } from 'next';
import Link from 'next/link';
import { ContactForm } from '@/components/contact-form';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Contact | TagStock',
  description: 'Please leave your inquiries about TagStock. We will respond as soon as possible.',
};

export default function ContactPage() {
  return (
    <>
      <Toaster position="top-center" />
      <div className="from-background to-muted/20 min-h-screen bg-linear-to-b">
        <div className="container mx-auto px-4 py-16">
          {/* Header */}
          <div className="mb-12 text-center">
            <h1 className="mb-4 text-4xl font-bold">Contact Us</h1>
            <p className="text-muted-foreground mx-auto max-w-2xl text-xl">
              Have any questions or need help?
              <br />
              Please feel free to contact us. We will respond quickly.
            </p>
          </div>

          <div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-2">
            {/* Contact Form */}
            <Card>
              <CardHeader>
                <CardTitle>Send Message</CardTitle>
                <CardDescription>
                  Fill out the form below and we will get back to you soon.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ContactForm />
              </CardContent>
            </Card>

            {/* FAQ */}
            <div className="space-y-6">
              <Card>
                <CardHeader>
                  <CardTitle>FAQ</CardTitle>
                  <CardDescription>Check out our FAQ before contacting us.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-6">
                    <div>
                      <h4 className="mb-2 font-semibold text-lg">Q. Is a free trial available?</h4>
                      <p className="text-muted-foreground text-sm">
                        Yes, free credits are provided upon signup to experience the service. You can test the tagging and IPTC features with these credits.
                      </p>
                    </div>
                    <div>
                      <h4 className="mb-2 font-semibold text-lg">Q. What is IPTC metadata?</h4>
                      <p className="text-muted-foreground text-sm">
                        IPTC is a standard for metadata in image files. TagStock automatically reads and writes IPTC headers so that your tags and descriptions stay with the file wherever it goes.
                      </p>
                    </div>
                    <div>
                      <h4 className="mb-2 font-semibold text-lg">Q. Can I upload multiple images?</h4>
                      <p className="text-muted-foreground text-sm">
                        Basic users can upload one image at a time. Pro plan users can use our multi-upload feature to process hundreds of images simultaneously.
                      </p>
                    </div>
                    <div>
                      <h4 className="mb-2 font-semibold text-lg">Q. What is the refund policy?</h4>
                      <p className="text-muted-foreground text-sm">
                        Unused credits can be fully refunded within 7 days of purchase. Once credits are used for processing images, they are non-refundable.
                      </p>
                    </div>
                    <div>
                      <h4 className="mb-2 font-semibold text-lg">Q. Is my payment information secure?</h4>
                      <p className="text-muted-foreground text-sm">
                        Yes, all payments are processed through Stripe, a world-class secure payment provider. We do not store your credit card information on our servers.
                      </p>
                    </div>
                    <div>
                      <h4 className="mb-2 font-semibold text-lg">Q. Which platforms are compatible?</h4>
                      <p className="text-muted-foreground text-sm">
                        The IPTC tags generated by TagStock are currently compatible with major stock platforms, including Adobe Stock and Shutterstock.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Back to Home */}
          <div className="mt-12 text-center">
            <Link href="/">
              <Button variant="ghost" className="cursor-pointer">
                Back to Home
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
